### PR TITLE
Feature/global variables

### PR DESCRIPTION
**Pull request by Shilohjones194**
Created components, "CreateEvent, Event, CreatePost, Post and Subject Button. It looks like the following two images. It still needs some adjustments on styling but they are clickable.

image

image

### CODE REVIEW

**Comment by Shilohjones194** [comment]
Both the "Create Post" and "create Event" buttons are separate from the cards. I will style those to show the difference a little late.

**Review by pablodlc — APPROVED** [review]
I deleted the App.js that was in this Push since I have one too.  I talked with Luke so we're deleting this one hoping to avoid a merge conflict

**Review by lilyhi — COMMENTED** [review]
Confused why it has "Click to view Calendar" as we do not have a calendar.

Also "Click to view more" I think this should just be a column of posts like the wireframe we made shows and not have a button to view more.

Is the login/sign up supposed to be in the header?

**Comment by Shilohjones194** [comment]
Both Buttons within the "post" and "event" cards have been changed to smaller buttons and verbiage was changed too. (as discussed in slack)

**Review by lilyhi — APPROVED** [review]

**Pull request merged**
